use std::sync::LazyLock;
use super::super::super::item::HPackItem;

/// 静态表 rfc9204-[Static Table](https://datatracker.ietf.org/doc/html/rfc9204#appendix-A)
pub(crate) static STATIC_TABLE: LazyLock<[HPackItem; 99]> = LazyLock::new(|| [
    HPackItem::new(":authority", ""),
    HPackItem::new(":path", "/"),
    HPackItem::new("age", "0"),
    HPackItem::new("content-disposition", ""),
    HPackItem::new("content-length", "0"),
    HPackItem::new("cookie", ""),
    HPackItem::new("date", ""),
    HPackItem::new("etag", ""),
    HPackItem::new("if-modified-since", ""),
    HPackItem::new("if-none-match", ""),
    HPackItem::new("last-modified", ""),
    HPackItem::new("link", ""),
    HPackItem::new("location", ""),
    HPackItem::new("referer", ""),
    HPackItem::new("set-cookie", ""),
    HPackItem::new(":method", "CONNECT"),
    HPackItem::new(":method", "DELETE"),
    HPackItem::new(":method", "GET"),
    HPackItem::new(":method", "HEAD"),
    HPackItem::new(":method", "OPTIONS"),
    HPackItem::new(":method", "POST"),
    HPackItem::new(":method", "PUT"),
    HPackItem::new(":scheme", "http"),
    HPackItem::new(":scheme", "https"),
    HPackItem::new(":status", "103"),
    HPackItem::new(":status", "200"),
    HPackItem::new(":status", "304"),
    HPackItem::new(":status", "404"),
    HPackItem::new(":status", "503"),
    HPackItem::new("accept", "*/*"),
    HPackItem::new("accept", "application/dns-message"),
    HPackItem::new("accept-encoding", "gzip, deflate, br"),
    HPackItem::new("accept-ranges", "bytes"),
    HPackItem::new("access-control-allow-headers", "cache-control"),
    HPackItem::new("access-control-allow-headers", "content-type"),
    HPackItem::new("access-control-allow-origin", "*"),
    HPackItem::new("cache-control", "max-age=0"),
    HPackItem::new("cache-control", "max-age=2592000"),
    HPackItem::new("cache-control", "max-age=604800"),
    HPackItem::new("cache-control", "no-cache"),
    HPackItem::new("cache-control", "no-store"),
    HPackItem::new("cache-control", "public, max-age=31536000"),
    HPackItem::new("content-encoding", "br"),
    HPackItem::new("content-encoding", "gzip"),
    HPackItem::new("content-type", "application/dns-message"),
    HPackItem::new("content-type", "application/javascript"),
    HPackItem::new("content-type", "application/json"),
    HPackItem::new("content-type", "application/x-www-form-urlencoded"),
    HPackItem::new("content-type", "image/gif"),
    HPackItem::new("content-type", "image/jpeg"),
    HPackItem::new("content-type", "image/png"),
    HPackItem::new("content-type", "text/css"),
    HPackItem::new("content-type", "text/html; charset=utf-8"),
    HPackItem::new("content-type", "text/plain"),
    HPackItem::new("content-type", "text/plain;charset=utf-8"),
    HPackItem::new("range", "bytes=0-"),
    HPackItem::new("strict-transport-security", "max-age=31536000"),
    HPackItem::new("strict-transport-security", "max-age=31536000; includesubdomains"),
    HPackItem::new("strict-transport-security", "max-age=31536000; includesubdomains; preload"),
    HPackItem::new("vary", "accept-encoding"),
    HPackItem::new("vary", "origin"),
    HPackItem::new("x-content-type-options", "nosniff"),
    HPackItem::new("x-xss-protection", "1; mode=block"),
    HPackItem::new(":status", "100"),
    HPackItem::new(":status", "204"),
    HPackItem::new(":status", "206"),
    HPackItem::new(":status", "302"),
    HPackItem::new(":status", "400"),
    HPackItem::new(":status", "403"),
    HPackItem::new(":status", "421"),
    HPackItem::new(":status", "425"),
    HPackItem::new(":status", "500"),
    HPackItem::new("accept-language", ""),
    HPackItem::new("access-control-allow-credentials", "FALSE"),
    HPackItem::new("access-control-allow-credentials", "TRUE"),
    HPackItem::new("access-control-allow-headers", "*"),
    HPackItem::new("access-control-allow-methods", "get"),
    HPackItem::new("access-control-allow-methods", "get, post, options"),
    HPackItem::new("access-control-allow-methods", "options"),
    HPackItem::new("access-control-expose-headers", "content-length"),
    HPackItem::new("access-control-request-headers", "content-type"),
    HPackItem::new("access-control-request-method", "get"),
    HPackItem::new("access-control-request-method", "post"),
    HPackItem::new("alt-svc", "clear"),
    HPackItem::new("authorization", ""),
    HPackItem::new("content-security-policy", "script-src 'none'; object-src 'none'; base-uri 'none'"),
    HPackItem::new("early-data", "1"),
    HPackItem::new("expect-ct", ""),
    HPackItem::new("forwarded", ""),
    HPackItem::new("if-range", ""),
    HPackItem::new("origin", ""),
    HPackItem::new("purpose", ""),
    HPackItem::new("server", ""),
    HPackItem::new("timing-allow-origin", "*"),
    HPackItem::new("upgrade-insecure-requests", "1"),
    HPackItem::new("user-agent", ""),
    HPackItem::new("x-forwarded-for", ""),
    HPackItem::new("x-frame-options", ""),
    HPackItem::new("x-frame-options", ""),
]);
