use std::borrow::Cow;
use super::super::super::item::{PackItem, pack_item};

/// 静态表 rfc9204-[Static Table](https://datatracker.ietf.org/doc/html/rfc9204#appendix-A)
pub(crate) static STATIC_TABLE: [PackItem; 99] = [
    pack_item!(":authority", ""),
    pack_item!(":path", "/"),
    pack_item!("age", "0"),
    pack_item!("content-disposition", ""),
    pack_item!("content-length", "0"),
    pack_item!("cookie", ""),
    pack_item!("date", ""),
    pack_item!("etag", ""),
    pack_item!("if-modified-since", ""),
    pack_item!("if-none-match", ""),
    pack_item!("last-modified", ""),
    pack_item!("link", ""),
    pack_item!("location", ""),
    pack_item!("referer", ""),
    pack_item!("set-cookie", ""),
    pack_item!(":method", "CONNECT"),
    pack_item!(":method", "DELETE"),
    pack_item!(":method", "GET"),
    pack_item!(":method", "HEAD"),
    pack_item!(":method", "OPTIONS"),
    pack_item!(":method", "POST"),
    pack_item!(":method", "PUT"),
    pack_item!(":scheme", "http"),
    pack_item!(":scheme", "https"),
    pack_item!(":status", "103"),
    pack_item!(":status", "200"),
    pack_item!(":status", "304"),
    pack_item!(":status", "404"),
    pack_item!(":status", "503"),
    pack_item!("accept", "*/*"),
    pack_item!("accept", "application/dns-message"),
    pack_item!("accept-encoding", "gzip, deflate, br"),
    pack_item!("accept-ranges", "bytes"),
    pack_item!("access-control-allow-headers", "cache-control"),
    pack_item!("access-control-allow-headers", "content-type"),
    pack_item!("access-control-allow-origin", "*"),
    pack_item!("cache-control", "max-age=0"),
    pack_item!("cache-control", "max-age=2592000"),
    pack_item!("cache-control", "max-age=604800"),
    pack_item!("cache-control", "no-cache"),
    pack_item!("cache-control", "no-store"),
    pack_item!("cache-control", "public, max-age=31536000"),
    pack_item!("content-encoding", "br"),
    pack_item!("content-encoding", "gzip"),
    pack_item!("content-type", "application/dns-message"),
    pack_item!("content-type", "application/javascript"),
    pack_item!("content-type", "application/json"),
    pack_item!("content-type", "application/x-www-form-urlencoded"),
    pack_item!("content-type", "image/gif"),
    pack_item!("content-type", "image/jpeg"),
    pack_item!("content-type", "image/png"),
    pack_item!("content-type", "text/css"),
    pack_item!("content-type", "text/html; charset=utf-8"),
    pack_item!("content-type", "text/plain"),
    pack_item!("content-type", "text/plain;charset=utf-8"),
    pack_item!("range", "bytes=0-"),
    pack_item!("strict-transport-security", "max-age=31536000"),
    pack_item!("strict-transport-security", "max-age=31536000; includesubdomains"),
    pack_item!("strict-transport-security", "max-age=31536000; includesubdomains; preload"),
    pack_item!("vary", "accept-encoding"),
    pack_item!("vary", "origin"),
    pack_item!("x-content-type-options", "nosniff"),
    pack_item!("x-xss-protection", "1; mode=block"),
    pack_item!(":status", "100"),
    pack_item!(":status", "204"),
    pack_item!(":status", "206"),
    pack_item!(":status", "302"),
    pack_item!(":status", "400"),
    pack_item!(":status", "403"),
    pack_item!(":status", "421"),
    pack_item!(":status", "425"),
    pack_item!(":status", "500"),
    pack_item!("accept-language", ""),
    pack_item!("access-control-allow-credentials", "FALSE"),
    pack_item!("access-control-allow-credentials", "TRUE"),
    pack_item!("access-control-allow-headers", "*"),
    pack_item!("access-control-allow-methods", "get"),
    pack_item!("access-control-allow-methods", "get, post, options"),
    pack_item!("access-control-allow-methods", "options"),
    pack_item!("access-control-expose-headers", "content-length"),
    pack_item!("access-control-request-headers", "content-type"),
    pack_item!("access-control-request-method", "get"),
    pack_item!("access-control-request-method", "post"),
    pack_item!("alt-svc", "clear"),
    pack_item!("authorization", ""),
    pack_item!("content-security-policy", "script-src 'none'; object-src 'none'; base-uri 'none'"),
    pack_item!("early-data", "1"),
    pack_item!("expect-ct", ""),
    pack_item!("forwarded", ""),
    pack_item!("if-range", ""),
    pack_item!("origin", ""),
    pack_item!("purpose", ""),
    pack_item!("server", ""),
    pack_item!("timing-allow-origin", "*"),
    pack_item!("upgrade-insecure-requests", "1"),
    pack_item!("user-agent", ""),
    pack_item!("x-forwarded-for", ""),
    pack_item!("x-frame-options", ""),
    pack_item!("x-frame-options", ""),
];
