use std::borrow::Cow;
use super::super::super::item::{PackItem, pack_item};

/// 静态表 rfc7541-Static Table Definition
pub(crate) static STATIC_TABLE: [PackItem; 61] = [
    pack_item!(":authority", ""),
    pack_item!(":method", "GET"),
    pack_item!(":method", "POST"),
    pack_item!(":path", "/"),
    pack_item!(":path", "/index.html"),
    pack_item!(":scheme", "http"),
    pack_item!(":scheme", "https"),
    pack_item!(":status", "200"),
    pack_item!(":status", "204"),
    pack_item!(":status", "206"),
    pack_item!(":status", "304"),
    pack_item!(":status", "400"),
    pack_item!(":status", "404"),
    pack_item!(":status", "500"),
    pack_item!("accept-charset", ""),
    pack_item!("accept-encoding", "gzip, deflate"),
    pack_item!("accept-language", ""),
    pack_item!("accept-ranges", ""),
    pack_item!("accept", ""),
    pack_item!("access-control-allow-origin", ""),
    pack_item!("age", ""),
    pack_item!("allow", ""),
    pack_item!("authorization", ""),
    pack_item!("cache-control", ""),
    pack_item!("content-disposition", ""),
    pack_item!("content-encoding", ""),
    pack_item!("content-language", ""),
    pack_item!("content-length", ""),
    pack_item!("content-location", ""),
    pack_item!("content-range", ""),
    pack_item!("content-type", ""),
    pack_item!("cookie", ""),
    pack_item!("date", ""),
    pack_item!("etag", ""),
    pack_item!("expect", ""),
    pack_item!("expires", ""),
    pack_item!("from", ""),
    pack_item!("host", ""),
    pack_item!("if-match", ""),
    pack_item!("if-modified-since", ""),
    pack_item!("if-none-match", ""),
    pack_item!("if-range", ""),
    pack_item!("if-unmodified-since", ""),
    pack_item!("last-modified", ""),
    pack_item!("link", ""),
    pack_item!("location", ""),
    pack_item!("max-forwards", ""),
    pack_item!("proxy-authenticate", ""),
    pack_item!("proxy-authorization", ""),
    pack_item!("range", ""),
    pack_item!("referer", ""),
    pack_item!("refresh", ""),
    pack_item!("retry-after", ""),
    pack_item!("server", ""),
    pack_item!("set-cookie", ""),
    pack_item!("strict-transport-security", ""),
    pack_item!("transfer-encoding", ""),
    pack_item!("user-agent", ""),
    pack_item!("vary", ""),
    pack_item!("via", ""),
    pack_item!("www-authenticate", ""),
];
