name: github
#git commit -m "修复bug [skip actions]"
#git commit -m "更新功能 [skip ci]"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --package reqrio --release --features export
#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.9.x"
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/reqrio-py" >> $GITHUB_ENV
      - name: Run Python FFI Test
        run: python reqrio-py/tests/test_session.py
#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: "24"
#      - name: Install Node deps
#        run: |
#          npm init -y
#          npm i ffi-napi
#          npm i ref-napi

      - name: Run Node FFI Test
        run: node reqrio-js/test.js
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Install MSVC
#        uses: ilammy/msvc-dev-cmd@v1
#        with:
#          arch: x64
      - name: build
        run: cargo build --package reqrio --release --features export
#      - name: Setup Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: "3.9.7"
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}\\reqrio-py" >> $env:GITHUB_ENV
      - name: Run Python FFI Test
        run: python reqrio-py/tests/test_session.py
      - name: Install Node deps
        run: |
#          npm init -y
          npm i ffi-napi
          npm i ref-napi

      - name: Run Node FFI Test
        run: node reqrio-js/test.js